# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drip',
            name='frequency',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
